version: '3.9'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog-api

    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

    ports:
      - "5000:8080"

    depends_on:
      - mongo

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseSettings__ConnectionString=mongodb://mongo:27017
      - DatabaseSettings__DatabaseName=CatalogDb

    networks:
      - catalog-network

  mongo:
    image: mongo:7
    container_name: catalog-mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    networks:
      - catalog-network
 



  discountdb:
    image: postgres:17

    container_name: discount-postgres

    environment:
      POSTGRES_DB: DiscountDb
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Saadpy11@

    restart: always

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - catalog-network 
      
  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      - discountdb

    networks:
      - catalog-network      
      
      
       
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket-api

    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

    ports:
      - "8001:8080"

    depends_on:
      - basketdb

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - CacheSettings__ConnectionString=basketdb:6379
      - "DiscountSettings__DiscountUrl=http://discount.api:8080"

    networks:
      - catalog-network

  basketdb:
    image: redis:alpine
    container_name: basketdb

    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - catalog-network




  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi

    container_name: discount-api

    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile

    ports:
      - "8002:8080"

    depends_on:
      - discountdb

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PostgressConnection=Host=discountdb;Port=5432;Database=DiscountDb;Username=Admin;Password=Saadpy11@

    networks:
      - catalog-network

volumes:
  mongo_data:
  redis_data:
  postgres_data:
networks:
  catalog-network:
